#!/usr/bin/env Rscript
# Seeded Seurat v5 layer integration. Usage: seurat_v5_integration.R INPUT.rds OUTPUT.rds batch RPCAIntegration
args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 4) stop("Usage: seurat_v5_integration.R INPUT.rds OUTPUT.rds batch_key method")
suppressPackageStartupMessages(library(Seurat))
input <- args[[1]]; output <- args[[2]]; batch_key <- args[[3]]; method_name <- args[[4]]
merged <- readRDS(input)
if (!batch_key %in% colnames(merged[[]])) stop(sprintf("Missing batch key: %s", batch_key))
method <- get0(method_name, mode = "function", inherits = TRUE)
if (is.null(method)) stop(sprintf("%s is unavailable; FastMNNIntegration/scVIIntegration require SeuratWrappers", method_name))
set.seed(0)
options(future.globals.maxSize = 4 * 1024^3)
merged[["RNA"]] <- split(merged[["RNA"]], f = merged[[batch_key, drop = TRUE]])
merged <- NormalizeData(merged, verbose = FALSE)
merged <- FindVariableFeatures(merged, verbose = FALSE)
merged <- ScaleData(merged, verbose = FALSE)
merged <- RunPCA(merged, npcs = 50, verbose = FALSE)
new_reduction <- paste0("integrated.", tolower(gsub("Integration$", "", method_name)))
merged <- IntegrateLayers(merged, method = method, orig.reduction = "pca", new.reduction = new_reduction, verbose = FALSE)
merged <- JoinLayers(merged)
merged <- FindNeighbors(merged, reduction = new_reduction, dims = 1:30, verbose = FALSE)
merged <- FindClusters(merged, resolution = 0.5, verbose = FALSE)
merged <- RunUMAP(merged, reduction = new_reduction, dims = 1:30, seed.use = 0, verbose = FALSE)
saveRDS(merged, output)
